# Generated by Django 5.2.4 on 2025-07-29 15:07

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Locality",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "typical_weather",
                    models.CharField(
                        blank=True, choices=[("cloudy", "Cloudy")], max_length=10
                    ),
                ),
            ],
        ),
    ]
