# Generated by Django 5.2.4 on 2025-07-29 15:07

from django.db import migrations


def bogus_weather(apps, schema_editor):
    Locality = apps.get_model("weather", "Locality")

    Locality(name="Delhi", typical_weather="sunny").save()
    Locality(name="Porto", typical_weather="sunny").save()
    Locality(name="Amsterdam", typical_weather="rainy").save()


class Migration(migrations.Migration):
    dependencies = [
        ("weather", "0001_initial"),
    ]

    operations = [migrations.RunPython(bogus_weather)]
